sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t alfredocm80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alfredocm80/docker-react npm run test