sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t alfredocm80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alfredocm80/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-XXXXXXXXXXXX"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  Secert_access_key:
    secure: "$AWS_SECRET_KEY"
